version: "3.8"

services:
  database:
    container_name: user-database-spring
    image: mysql
    networks:
      - springboot-db-net
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - my-db:/var/lib/mysql

  app:
    container_name: user-api-spring
    build:
      context: .
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - springboot-db-net


volumes:
  my-db:

networks:
  springboot-db-net: