services:
  database:
    container_name: user-database-spring
    image: "mysql:8.0-oracle"
    networks:
      - springboot-db-net
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - /data/spring-app
      - "./script/generate.sql:/docker-entrypoint-initdb.d/1.sql"

  app:
    container_name: user-api-spring
    build:
      context: .
    depends_on:
      database:
        condition: service_started
        restart: true
    ports:
      - 8080:8080
    networks:
      - springboot-db-net

networks:
  springboot-db-net:
    driver: bridge