spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://user-database-spring:3306/db
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  servlet:
    context-path: /api/v1
    
    
logging: 
   level: 
      com.zaxxer.hikari.hibernate.HikariConnectionProvider: DEBUG 
      com.zaxxer.hikari: DEBUG